apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: my-html-files
          hostPath:
            path: /usr/share/nginx/AFK
      containers:
        - name: nginx-container
          image: alperanfk/test7:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-html-files
              mountPath: /usr/share/nginx/AFK